Домашняя работа 5
t-o-n-y-p/AntonPeretrukhin_LevelUP pull request #8
Opened 2021-06-16 23:31 UTC by t-o-n-y-p

2021-06-17 10:06 UTC, khda91 requested changes
Прошу исправить замечания

2021-06-17 10:06 UTC, khda91 commented on pom.xml
> +            </build>
а зачем в каждый профиль добавлять `build` секцию с плагином? 
Может можно как-то через проперти это сделать?

2021-06-19 10:19 UTC, t-o-n-y-p commented on pom.xml
> +            </build>
Исправлено

2021-06-25 13:28 UTC, khda91 approved these changes
homework is accepted

2021-06-25 13:28 UTC, merged